/** @format */

declare module "akaneko";
declare module "mathjs";
declare module "node-fetch";
declare module "genius-lyrics";
declare module "genshin-db";
declare module "mywaifulist-scraper";
declare module "mangadex-full-api";
declare module "mal-scraper";
declare module "wikipedia";
declare module "anime-wallpaper";
declare module "translate-google";
declare module "animequotes";
declare module "node-periodic-table";
declare module "oakdex-pokedex";
declare module "ptable";
declare module "node-myanimelist";
declare module "trace.moe.ts";
declare module "anilist-node";
declare module "pokedex-promise-v2";
declare module "imgbb-uploader";
declare module "lolis.life";
declare module "anime-wallpapers";
declare module "discord-image-generation";
declare module "shentai";
declare module "vtuber-wiki";
declare module "discord-welcome-card";
declare module "discord-canvas";
declare module "parse-ms-js";
declare module "@shineiichijo/marika";
declare module "anime-quiz";
​
