/** @format */

declare module "akaneko";
declare module "mathjs";
declare module "node-fetch";
declare module "genius-lyrics";
declare module "genshin-db";
declare module "mywaifulist-scraper";
declare module "mangadex-full-api";
declare module "mal-scraper";
declare module "wikipedia";
declare module "anime-wallpaper";
declare module "translate-google";
declare module "animequotes";
declare module "mailist";
declare module "@marsron/google-image";
declare module "node-periodic-table";
declare module "oakdex-pokedex";
declare module "ptable";
declare module "node-myanimelist";
declare module "trace.moe.ts";
declare module "anilist-node";
declare module "pokedex-promise-v2";
declare module "imgbb-uploader";
declare module "lolis.life";
declare module "lolis.life";
declare module "anime-wallpapers";
